name: Build Packages

on:
  pull_request:
    branches:
      - master

jobs:
  build-packages:
    runs-on: ubuntu-latest

    env:
      NIXPKGS_ALLOW_UNFREE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build all packages on x64
        run: nix flake show --json | jq  '.packages."x86_64-linux"|keys[]'| xargs -I {} nix build .#{} --impure
